### ISSUE TITLE
Run DB migrations in deploy

### ISSUE THREAD

**Issue by danielcompton** [clojars/infrastructure#10]
I'm not quite sure what do about DB migrations, possibly they should be a resource in the uberjar? That way we always know we've got the right schema for each version.

**Comment by tobias** [comment]
The migrations themselves come from https://github.com/clojars/clojars-web/tree/master/src/clojars/db/migrate.clj, but do depend on `clojars.sql`, which is currently in the root of the project, but could easily be moved in to `resources/` so it ends up in the uberjar.
