### ISSUE TITLE
Handle deleted JARs

### ISSUE THREAD

**Issue by danielcompton** [clojars/infrastructure#12]
Not quite sure what server config is needed here, @tobias what's the process for deleting JARs?

**Comment by tobias** [comment]
The current process is to ssh in, attach to the repl, then use the fns in https://github.com/clojars/clojars-web/tree/master/src/clojars/admin.clj. We used to use shell scripts, but that caused contention issues with the sqlite db. All db access within the app uses https://github.com/clojars/clojars-web/tree/master/src/clojars/db.clj#L174 to prevent db contention.

I don't think we need any ansible config for handling deletions, we can continue to do it via ssh+repl.

**Comment by danielcompton** [comment]
Cool, I'll close this for now. Ansible does allow multiple playbook + custom parameters, so it would be possible to have a `delete-jar.yml` playbook to automate this process. But we'll leave it for now.
