### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by danielcompton** [clojars/infrastructure#39]
We would like to change the license to MIT. This would make it possible for people to derive new works from this config for internal purposes without having to redistribute them. Under normal usage, sharing the changes would not be required, but it [would if you distributed it](https://www.eclipse.org/legal/eplfaq.php#MODNODIST) (e.g. as part of a package that runs on client sites)

To allow for the relicensing, reply to this issue with "I Agree". If you don't agree then feel free to discuss this more here.

- [x] @danielcompton
- [x] @tobias 
- [x] @kahunamoore 
- [x] @spencercrissman 
- [x] @hyPiRion 

Thanks!

**Comment by danielcompton** [comment]
I agree.

**Comment by tobias** [comment]
I agree.

**Comment by spencercrissman** [comment]
I agree.

**Comment by hypirion** [comment]
I agree.

**Comment by kahunamoore** [comment]
I agree.

**Comment by danielcompton** [comment]
Great!
